/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.view.admin;

import javax.swing.JPanel;

/**
 *
 * @author PAVILION
 */
public class NavigationPane extends javax.swing.JPanel {

    /**
     * Creates new form NavigationPane2
     */
    public NavigationPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationPane = new javax.swing.JPanel();
        manageUserTab = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        imgUser = new javax.swing.JLabel();
        manageAppointmentTab = new javax.swing.JPanel();
        lblAppointment = new javax.swing.JLabel();
        imgAppointment = new javax.swing.JLabel();
        manageVaccineTab = new javax.swing.JPanel();
        lblVaccine = new javax.swing.JLabel();
        imgVaccine = new javax.swing.JLabel();
        viewReportTab = new javax.swing.JPanel();
        lblReport = new javax.swing.JLabel();
        imgReport = new javax.swing.JLabel();
        manageVaccineCentreTab = new javax.swing.JPanel();
        lblVaccineCentre = new javax.swing.JLabel();
        imgVaccineCentre = new javax.swing.JLabel();
        manageVaccinationTab = new javax.swing.JPanel();
        lblVaccination = new javax.swing.JLabel();
        imgVaccination = new javax.swing.JLabel();
        manageAdminTab = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        imgAdmin = new javax.swing.JLabel();
        logoutTab = new javax.swing.JPanel();
        lblLogOut = new javax.swing.JLabel();
        imgLogOut = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        appImg = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        navigationPane.setBackground(new java.awt.Color(245, 245, 245));
        navigationPane.setPreferredSize(new java.awt.Dimension(320, 720));

        manageUserTab.setBackground(new java.awt.Color(245, 245, 245));
        manageUserTab.setName("manageUserTab"); // NOI18N

        lblUser.setBackground(new java.awt.Color(209, 209, 209));
        lblUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(79, 79, 79));
        lblUser.setText("Manage User");
        lblUser.setToolTipText("");

        imgUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/people.png"))); // NOI18N

        javax.swing.GroupLayout manageUserTabLayout = new javax.swing.GroupLayout(manageUserTab);
        manageUserTab.setLayout(manageUserTabLayout);
        manageUserTabLayout.setHorizontalGroup(
            manageUserTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageUserTabLayout.setVerticalGroup(
            manageUserTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(manageUserTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblUser)
                .addGap(17, 17, 17))
        );

        manageAppointmentTab.setBackground(new java.awt.Color(245, 245, 245));
        manageAppointmentTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        manageAppointmentTab.setName("manageAppointmentTab"); // NOI18N

        lblAppointment.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblAppointment.setForeground(new java.awt.Color(79, 79, 79));
        lblAppointment.setText("Manage Appointment");
        lblAppointment.setToolTipText("");

        imgAppointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/calendar.png"))); // NOI18N

        javax.swing.GroupLayout manageAppointmentTabLayout = new javax.swing.GroupLayout(manageAppointmentTab);
        manageAppointmentTab.setLayout(manageAppointmentTabLayout);
        manageAppointmentTabLayout.setHorizontalGroup(
            manageAppointmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAppointmentTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgAppointment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAppointment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageAppointmentTabLayout.setVerticalGroup(
            manageAppointmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgAppointment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(manageAppointmentTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblAppointment)
                .addGap(17, 17, 17))
        );

        manageVaccineTab.setBackground(new java.awt.Color(245, 245, 245));
        manageVaccineTab.setName("manageVaccineTab"); // NOI18N

        lblVaccine.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblVaccine.setForeground(new java.awt.Color(79, 79, 79));
        lblVaccine.setText("Manage Vaccine");
        lblVaccine.setToolTipText("");

        imgVaccine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/vaccines.png"))); // NOI18N

        javax.swing.GroupLayout manageVaccineTabLayout = new javax.swing.GroupLayout(manageVaccineTab);
        manageVaccineTab.setLayout(manageVaccineTabLayout);
        manageVaccineTabLayout.setHorizontalGroup(
            manageVaccineTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageVaccineTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgVaccine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVaccine)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageVaccineTabLayout.setVerticalGroup(
            manageVaccineTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgVaccine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(manageVaccineTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblVaccine)
                .addGap(17, 17, 17))
        );

        viewReportTab.setBackground(new java.awt.Color(245, 245, 245));
        viewReportTab.setName("viewReportTab"); // NOI18N

        lblReport.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblReport.setForeground(new java.awt.Color(79, 79, 79));
        lblReport.setText("View Report");
        lblReport.setToolTipText("");

        imgReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/notes.png"))); // NOI18N

        javax.swing.GroupLayout viewReportTabLayout = new javax.swing.GroupLayout(viewReportTab);
        viewReportTab.setLayout(viewReportTabLayout);
        viewReportTabLayout.setHorizontalGroup(
            viewReportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewReportTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewReportTabLayout.setVerticalGroup(
            viewReportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(viewReportTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblReport)
                .addGap(17, 17, 17))
        );

        manageVaccineCentreTab.setBackground(new java.awt.Color(245, 245, 245));
        manageVaccineCentreTab.setName("manageVaccineCentreTab"); // NOI18N

        lblVaccineCentre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblVaccineCentre.setForeground(new java.awt.Color(79, 79, 79));
        lblVaccineCentre.setText("Manage Vaccine Centre");
        lblVaccineCentre.setToolTipText("");

        imgVaccineCentre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/centre.png"))); // NOI18N

        javax.swing.GroupLayout manageVaccineCentreTabLayout = new javax.swing.GroupLayout(manageVaccineCentreTab);
        manageVaccineCentreTab.setLayout(manageVaccineCentreTabLayout);
        manageVaccineCentreTabLayout.setHorizontalGroup(
            manageVaccineCentreTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageVaccineCentreTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgVaccineCentre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVaccineCentre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageVaccineCentreTabLayout.setVerticalGroup(
            manageVaccineCentreTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgVaccineCentre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(manageVaccineCentreTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblVaccineCentre)
                .addGap(17, 17, 17))
        );

        manageVaccinationTab.setBackground(new java.awt.Color(245, 245, 245));
        manageVaccinationTab.setName("manageVaccinationTab"); // NOI18N

        lblVaccination.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblVaccination.setForeground(new java.awt.Color(79, 79, 79));
        lblVaccination.setText("Manage Vaccination");
        lblVaccination.setToolTipText("");

        imgVaccination.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/injection.png"))); // NOI18N

        javax.swing.GroupLayout manageVaccinationTabLayout = new javax.swing.GroupLayout(manageVaccinationTab);
        manageVaccinationTab.setLayout(manageVaccinationTabLayout);
        manageVaccinationTabLayout.setHorizontalGroup(
            manageVaccinationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageVaccinationTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgVaccination)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVaccination)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageVaccinationTabLayout.setVerticalGroup(
            manageVaccinationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgVaccination, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(manageVaccinationTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblVaccination)
                .addGap(17, 17, 17))
        );

        manageAdminTab.setBackground(new java.awt.Color(245, 245, 245));
        manageAdminTab.setName("manageAdminTab"); // NOI18N

        lblAdmin.setBackground(new java.awt.Color(209, 209, 209));
        lblAdmin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(79, 79, 79));
        lblAdmin.setText("Manage Admin");
        lblAdmin.setToolTipText("");

        imgAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin.png"))); // NOI18N

        javax.swing.GroupLayout manageAdminTabLayout = new javax.swing.GroupLayout(manageAdminTab);
        manageAdminTab.setLayout(manageAdminTabLayout);
        manageAdminTabLayout.setHorizontalGroup(
            manageAdminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAdminTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageAdminTabLayout.setVerticalGroup(
            manageAdminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(manageAdminTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblAdmin)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        logoutTab.setBackground(new java.awt.Color(245, 245, 245));
        logoutTab.setName("logoutTab"); // NOI18N

        lblLogOut.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblLogOut.setForeground(new java.awt.Color(79, 79, 79));
        lblLogOut.setText("Log Out");

        imgLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N

        javax.swing.GroupLayout logoutTabLayout = new javax.swing.GroupLayout(logoutTab);
        logoutTab.setLayout(logoutTabLayout);
        logoutTabLayout.setHorizontalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutTabLayout.setVerticalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        logoPanel.setBackground(new java.awt.Color(245, 245, 245));
        logoPanel.setName(""); // NOI18N

        appImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/app-large.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(appImg)
                .addGap(110, 110, 110))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(appImg)
                .addContainerGap())
        );

        javax.swing.GroupLayout navigationPaneLayout = new javax.swing.GroupLayout(navigationPane);
        navigationPane.setLayout(navigationPaneLayout);
        navigationPaneLayout.setHorizontalGroup(
            navigationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageAppointmentTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageVaccineTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewReportTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageUserTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageVaccineCentreTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageVaccinationTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageAdminTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navigationPaneLayout.setVerticalGroup(
            navigationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(manageUserTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageAdminTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageAppointmentTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageVaccineTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageVaccineCentreTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageVaccinationTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewReportTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setForeground(new java.awt.Color(79, 79, 79));
        contentPanel.setToolTipText("");
        contentPanel.setPreferredSize(new java.awt.Dimension(960, 720));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigationPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //getter setter
    public JPanel getContentPanel() {
        return contentPanel;
    }

  // controller
    public void addTabListeners(java.awt.event.MouseAdapter m) {
      manageAdminTab.addMouseListener(m);
      manageUserTab.addMouseListener(m);
      manageVaccineTab.addMouseListener(m);
      manageVaccineCentreTab.addMouseListener(m);
      manageVaccinationTab.addMouseListener(m);
      manageAppointmentTab.addMouseListener(m);
      viewReportTab.addMouseListener(m);
      logoutTab.addMouseListener(m);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appImg;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel imgAdmin;
    private javax.swing.JLabel imgAppointment;
    private javax.swing.JLabel imgLogOut;
    private javax.swing.JLabel imgReport;
    private javax.swing.JLabel imgUser;
    private javax.swing.JLabel imgVaccination;
    private javax.swing.JLabel imgVaccine;
    private javax.swing.JLabel imgVaccineCentre;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAppointment;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblVaccination;
    private javax.swing.JLabel lblVaccine;
    private javax.swing.JLabel lblVaccineCentre;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel logoutTab;
    private javax.swing.JPanel manageAdminTab;
    private javax.swing.JPanel manageAppointmentTab;
    private javax.swing.JPanel manageUserTab;
    private javax.swing.JPanel manageVaccinationTab;
    private javax.swing.JPanel manageVaccineCentreTab;
    private javax.swing.JPanel manageVaccineTab;
    private javax.swing.JPanel navigationPane;
    private javax.swing.JPanel viewReportTab;
    // End of variables declaration//GEN-END:variables
}
