package assignment.view.admin;

import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author PAVILION
 */
public class UserManagement extends javax.swing.JPanel {

    /**
     * Creates new form contentPane
     */
    public UserManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        inputForm = new javax.swing.JPanel();
        txtId = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        txtName = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JLabel();
        inputPhone = new javax.swing.JTextField();
        txtGender = new javax.swing.JLabel();
        txtIC = new javax.swing.JLabel();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        txtLocality = new javax.swing.JLabel();
        btnMalaysian = new javax.swing.JRadioButton();
        btnForeigner = new javax.swing.JRadioButton();
        birthDate = new javax.swing.JLabel();
        inputBirthDate = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        txtVacStatus = new javax.swing.JLabel();
        inputIC = new javax.swing.JTextField();
        btnUnvac = new javax.swing.JRadioButton();
        btnPartial = new javax.swing.JRadioButton();
        btnFull = new javax.swing.JRadioButton();
        inputPassword = new javax.swing.JPasswordField();
        btnAddUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        btnRemoveUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        txtSearch = new javax.swing.JLabel();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        title = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(960, 720));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(960, 720));
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(20);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 1200));

        inputForm.setBackground(new java.awt.Color(255, 255, 255));
        inputForm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 63, 65), 1, true));
        inputForm.setPreferredSize(new java.awt.Dimension(250, 760));

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(60, 63, 65));
        txtId.setText("User ID");

        inputId.setEditable(false);
        inputId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(60, 63, 65));
        txtName.setText("Name");

        inputName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(60, 63, 65));
        txtEmail.setText("Email");

        inputEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(60, 63, 65));
        txtPhone.setText("Phone");

        inputPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGender.setForeground(new java.awt.Color(60, 63, 65));
        txtGender.setText("Gender");

        txtIC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIC.setForeground(new java.awt.Color(60, 63, 65));
        txtIC.setText("IC/Passport Number");

        btnMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnMale);
        btnMale.setForeground(new java.awt.Color(79, 79, 79));
        btnMale.setText("Male");

        btnFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnFemale);
        btnFemale.setForeground(new java.awt.Color(79, 79, 79));
        btnFemale.setText("Female");

        txtLocality.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLocality.setForeground(new java.awt.Color(60, 63, 65));
        txtLocality.setText("Locality");

        btnMalaysian.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(btnMalaysian);
        btnMalaysian.setForeground(new java.awt.Color(79, 79, 79));
        btnMalaysian.setText("Malaysian");

        btnForeigner.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(btnForeigner);
        btnForeigner.setForeground(new java.awt.Color(79, 79, 79));
        btnForeigner.setText("Foreigner");

        birthDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birthDate.setForeground(new java.awt.Color(60, 63, 65));
        birthDate.setText("Birth Date");

        inputBirthDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(60, 63, 65));
        password.setText("Password");

        txtVacStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtVacStatus.setForeground(new java.awt.Color(60, 63, 65));
        txtVacStatus.setText("Vaccination Status");

        inputIC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnUnvac.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(btnUnvac);
        btnUnvac.setForeground(new java.awt.Color(79, 79, 79));
        btnUnvac.setText("Unvaccinated");

        btnPartial.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(btnPartial);
        btnPartial.setForeground(new java.awt.Color(79, 79, 79));
        btnPartial.setText("Partially Vaccinated");

        btnFull.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(btnFull);
        btnFull.setForeground(new java.awt.Color(79, 79, 79));
        btnFull.setText("Fully Vaccinated");

        javax.swing.GroupLayout inputFormLayout = new javax.swing.GroupLayout(inputForm);
        inputForm.setLayout(inputFormLayout);
        inputFormLayout.setHorizontalGroup(
            inputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFormLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(inputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPartial)
                    .addComponent(btnUnvac)
                    .addComponent(btnFull)
                    .addComponent(inputIC, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVacStatus)
                    .addComponent(txtPhone)
                    .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId)
                    .addComponent(txtName)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIC)
                    .addComponent(txtGender)
                    .addComponent(txtLocality)
                    .addGroup(inputFormLayout.createSequentialGroup()
                        .addGroup(inputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMalaysian)
                            .addComponent(btnMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFemale)
                            .addComponent(btnForeigner)))
                    .addComponent(birthDate)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputFormLayout.setVerticalGroup(
            inputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(birthDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMale)
                    .addComponent(btnFemale))
                .addGap(18, 18, 18)
                .addComponent(txtLocality)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMalaysian)
                    .addComponent(btnForeigner))
                .addGap(14, 14, 14)
                .addComponent(txtIC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputIC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtVacStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUnvac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPartial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFull)
                .addGap(30, 30, 30))
        );

        btnAddUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddUser.setText("Add User");

        btnEditUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditUser.setText("Edit User");

        btnRemoveUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemoveUser.setText("Remove User");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(600, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(620, 580));

        userTable.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel() {
        });
        userTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        userTable.setPreferredSize(null);
        userTable.setRowHeight(24);
        userTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(userTable);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(60, 63, 65));
        txtSearch.setText("Search Users:");

        inputSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSearch)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputForm, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setPreferredSize(new java.awt.Dimension(960, 70));

        jSeparator2.setPreferredSize(new java.awt.Dimension(960, 3));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(79, 79, 79));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Manage User");
        lblTitle.setInheritsPopupMenu(false);
        lblTitle.setPreferredSize(new java.awt.Dimension(960, 22));

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setTable(javax.swing.table.DefaultTableModel m) {
        userTable.setModel(m);
    }

    public javax.swing.table.TableModel getTableModel() {
        return userTable.getModel();
    }

    public javax.swing.JTable getTable() {
        return userTable;
    }    
    
    public javax.swing.JTextField[] getTextField() {
        javax.swing.JTextField[] textFields = {inputId, inputName, inputEmail, inputPassword, inputPhone, inputBirthDate, inputIC};
        return textFields;
    }

    public javax.swing.JRadioButton[] getButtons() {
        javax.swing.JRadioButton[] buttons = {btnMale, btnFemale, btnMalaysian, btnForeigner, btnUnvac, btnPartial, btnFull};
        return buttons;
    }

    public Object[] getFields() {
        Object[] fields = {inputId, inputName, inputEmail, inputPassword, inputPhone, inputBirthDate, buttonGroup1, buttonGroup2, inputIC, buttonGroup3};
        return fields;
    }

    public String getSearchField() {
      return inputSearch.getText();
    }

    //controller
    public void addUserTableMouseListener(java.awt.event.MouseListener l) {
        userTable.addMouseListener(l);
    }

    public void addTableAddListener(java.awt.event.ActionListener l) {
        // inventoryTable.addMouseListener(l);
        btnAddUser.addActionListener(l);
    }

    public void addTableDeleteListener(java.awt.event.ActionListener l){
        btnRemoveUser.addActionListener(l);
    }

    public void addTableEditListener(java.awt.event.ActionListener l) {
        btnEditUser.addActionListener(l);
    }

    public JRadioButton getBtnFemale() {
        return btnFemale;
    }

    public JRadioButton getBtnForeigner() {
        return btnForeigner;
    }

    public JRadioButton getBtnMalaysian() {
        return btnMalaysian;
    }

    public JRadioButton getBtnMale() {
        return btnMale;
    }

    public JTextField getInputBirthDate() {
        return inputBirthDate;
    }

    public JTextField getInputEmail() {
        return inputEmail;
    }

    public JPanel getInputForm() {
        return inputForm;
    }

    public JTextField getInputIC() {
        return inputIC;
    }

    public JTextField getInputId() {
        return inputId;
    }

    public JTextField getInputName() {
        return inputName;
    }

    public JTextField getInputPhone() {
        return inputPhone;
    }

    public void addSearchListener(java.awt.event.ActionListener l) {
      btnSearch.addActionListener(l);
    }

    public void addSearchDocumentListener(javax.swing.event.DocumentListener l) {
      inputSearch.getDocument().addDocumentListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthDate;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnForeigner;
    private javax.swing.JRadioButton btnFull;
    private javax.swing.JRadioButton btnMalaysian;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JRadioButton btnPartial;
    private javax.swing.JButton btnRemoveUser;
    private javax.swing.JButton btnSearch;
    private javax.swing.JRadioButton btnUnvac;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField inputBirthDate;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JPanel inputForm;
    private javax.swing.JTextField inputIC;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputName;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel password;
    private javax.swing.JPanel title;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtIC;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtLocality;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPhone;
    private javax.swing.JLabel txtSearch;
    private javax.swing.JLabel txtVacStatus;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
