package assignment.view.admin;

/**
 *
 * @author PAVILION
 */
public class VaccineCentreManagement extends javax.swing.JPanel {

    /**
     * Creates new form contentPane
     */
    public VaccineCentreManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        inputForm = new javax.swing.JPanel();
        txtCentreId = new javax.swing.JLabel();
        txtCentreName = new javax.swing.JLabel();
        inputCentreName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JLabel();
        inputLocation = new javax.swing.JTextField();
        txtCapacity = new javax.swing.JLabel();
        inputCapacity = new javax.swing.JTextField();
        inputId = new javax.swing.JTextField();
        btnAddCentre = new javax.swing.JButton();
        btnRemoveCentre = new javax.swing.JButton();
        btnEditCentre = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        centreTable = new javax.swing.JTable();
        title = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();
        txtSearch = new javax.swing.JLabel();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(960, 720));

        inputForm.setBackground(new java.awt.Color(255, 255, 255));
        inputForm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 63, 65), 1, true));
        inputForm.setPreferredSize(new java.awt.Dimension(250, 345));

        txtCentreId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCentreId.setForeground(new java.awt.Color(60, 63, 65));
        txtCentreId.setText("Centre ID");

        txtCentreName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCentreName.setForeground(new java.awt.Color(60, 63, 65));
        txtCentreName.setText("Centre Name");

        inputCentreName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLocation.setForeground(new java.awt.Color(60, 63, 65));
        txtLocation.setText("Location");

        inputLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtCapacity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCapacity.setForeground(new java.awt.Color(60, 63, 65));
        txtCapacity.setText("Capacity");

        inputCapacity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        inputId.setEditable(false);
        inputId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout inputFormLayout = new javax.swing.GroupLayout(inputForm);
        inputForm.setLayout(inputFormLayout);
        inputFormLayout.setHorizontalGroup(
            inputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFormLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(inputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCentreId)
                    .addComponent(txtCentreName)
                    .addComponent(inputCentreName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocation)
                    .addComponent(inputLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapacity)
                    .addComponent(inputCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputFormLayout.setVerticalGroup(
            inputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtCentreId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCentreName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCentreName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCapacity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnAddCentre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddCentre.setText("Add Centre");
        btnAddCentre.setPreferredSize(new java.awt.Dimension(250, 45));

        btnRemoveCentre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemoveCentre.setText("Remove Centre");
        btnRemoveCentre.setPreferredSize(new java.awt.Dimension(250, 45));

        btnEditCentre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditCentre.setText("Edit Centre");
        btnEditCentre.setPreferredSize(new java.awt.Dimension(250, 45));

        centreTable.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        centreTable.setModel(new javax.swing.table.DefaultTableModel() {
        });
        centreTable.setRowHeight(24);
        centreTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(centreTable);

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setPreferredSize(new java.awt.Dimension(960, 70));

        jSeparator2.setPreferredSize(new java.awt.Dimension(960, 3));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(79, 79, 79));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Manage Centre");
        lblTitle.setInheritsPopupMenu(false);
        lblTitle.setPreferredSize(new java.awt.Dimension(960, 22));

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(60, 63, 65));
        txtSearch.setText("Search Centres:");

        inputSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemoveCentre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditCentre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddCentre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(inputForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoveCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setTable(javax.swing.table.DefaultTableModel m) {
        centreTable.setModel(m);
    }

    public javax.swing.table.TableModel getTableModel() {
        return centreTable.getModel();
    }

    public javax.swing.JTable getTable() {
        return centreTable;
    }

    public javax.swing.JTextField[] getTextField() {
        javax.swing.JTextField[] textFields = {inputId, inputCentreName, inputLocation, inputCapacity};
        return textFields;
    }

    public String getSearchField() {
      return inputSearch.getText();
    }

    //controller
    public void addInventoryTableMouseListener(java.awt.event.MouseListener l) {
        centreTable.addMouseListener(l);
    }

    public void addTableAddListener(java.awt.event.ActionListener l) {
        // inventoryTable.addMouseListener(l);
        btnAddCentre.addActionListener(l);
    }

    public void addTableDeleteListener(java.awt.event.ActionListener l){
        btnRemoveCentre.addActionListener(l);
    }

    public void addTableEditListener(java.awt.event.ActionListener l) {
        btnEditCentre.addActionListener(l);
    }

    public void addSearchListener(java.awt.event.ActionListener l) {
      btnSearch.addActionListener(l);
    }

    public void addSearchDocumentListener(javax.swing.event.DocumentListener l) {
      inputSearch.getDocument().addDocumentListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCentre;
    private javax.swing.JButton btnEditCentre;
    private javax.swing.JButton btnRemoveCentre;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTable centreTable;
    private javax.swing.JTextField inputCapacity;
    private javax.swing.JTextField inputCentreName;
    private javax.swing.JPanel inputForm;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputLocation;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel title;
    private javax.swing.JLabel txtCapacity;
    private javax.swing.JLabel txtCentreId;
    private javax.swing.JLabel txtCentreName;
    private javax.swing.JLabel txtLocation;
    private javax.swing.JLabel txtSearch;
    // End of variables declaration//GEN-END:variables
}
