/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.view.auth;


import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/** @author rmrt1n */
public class SignupForm extends javax.swing.JPanel {

  /** Creates new form NewJPanel */
  public SignupForm() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        formContainer = new javax.swing.JPanel();
        formCard = new javax.swing.JPanel();
        inputPassword = new javax.swing.JPasswordField();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        title = new javax.swing.JLabel();
        inputPhone = new javax.swing.JTextField();
        inputIDNumber = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        phoneNumber = new javax.swing.JLabel();
        emailAddress = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        registerHere = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        citizenship = new javax.swing.JLabel();
        btnMalaysian = new javax.swing.JRadioButton();
        btnForeigner = new javax.swing.JRadioButton();
        password1 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        committeeHere = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        formContainer.setBackground(new java.awt.Color(255, 255, 255));
        formContainer.setPreferredSize(new java.awt.Dimension(375, 575));

        formCard.setOpaque(false);

        inputPassword.setPreferredSize(new java.awt.Dimension(95, 25));

        btnMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(btnMale);
        btnMale.setForeground(new java.awt.Color(79, 79, 79));
        btnMale.setSelected(true);
        btnMale.setText("Male");

        btnFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(btnFemale);
        btnFemale.setForeground(new java.awt.Color(79, 79, 79));
        btnFemale.setText("Female");

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Sign up");
        title.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(79, 79, 79));

        inputPhone.setPreferredSize(new java.awt.Dimension(95, 25));

        inputIDNumber.setPreferredSize(new java.awt.Dimension(95, 25));

        submitButton.setText("Sign up");
        submitButton.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        submitButton.setForeground(new java.awt.Color(79, 79, 79));
        submitButton.setMinimumSize(new java.awt.Dimension(23, 25));
        submitButton.setPreferredSize(new java.awt.Dimension(95, 25));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        phoneNumber.setText("Phone number");
        phoneNumber.setForeground(new java.awt.Color(79, 79, 79));

        emailAddress.setText("Email address");
        emailAddress.setForeground(new java.awt.Color(79, 79, 79));

        password.setText("Password");
        password.setForeground(new java.awt.Color(79, 79, 79));

        gender.setText("Gender");
        gender.setForeground(new java.awt.Color(79, 79, 79));

        id.setText("IC Number");
        id.setForeground(new java.awt.Color(79, 79, 79));

        registerHere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerHere.setText("Have an account? Sign in here");
        registerHere.setForeground(new java.awt.Color(51, 51, 255));

        inputName.setPreferredSize(new java.awt.Dimension(95, 25));

        name.setText("Name");
        name.setForeground(new java.awt.Color(79, 79, 79));

        citizenship.setText("Citizenship");
        citizenship.setForeground(new java.awt.Color(79, 79, 79));

        btnMalaysian.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnMalaysian);
        btnMalaysian.setForeground(new java.awt.Color(79, 79, 79));
        btnMalaysian.setSelected(true);
        btnMalaysian.setText("Malaysian");
        btnMalaysian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        btnForeigner.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnForeigner);
        btnForeigner.setForeground(new java.awt.Color(79, 79, 79));
        btnForeigner.setText("Foreigner");
        btnForeigner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        password1.setText("Birth Date");
        password1.setForeground(new java.awt.Color(79, 79, 79));

        javax.swing.GroupLayout formCardLayout = new javax.swing.GroupLayout(formCard);
        formCard.setLayout(formCardLayout);
        formCardLayout.setHorizontalGroup(
            formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputIDNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputEmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formCardLayout.createSequentialGroup()
                        .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumber)
                            .addComponent(emailAddress)
                            .addComponent(password)
                            .addComponent(gender)
                            .addComponent(id)
                            .addComponent(name)
                            .addComponent(citizenship)
                            .addGroup(formCardLayout.createSequentialGroup()
                                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMalaysian)
                                    .addComponent(btnMale))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFemale)
                                    .addComponent(btnForeigner)))
                            .addComponent(password1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(registerHere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formCardLayout.setVerticalGroup(
            formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMale)
                    .addComponent(btnFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(citizenship)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMalaysian)
                    .addComponent(btnForeigner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerHere)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        committeeHere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        committeeHere.setText("Committee");
        committeeHere.setForeground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout formContainerLayout = new javax.swing.GroupLayout(formContainer);
        formContainer.setLayout(formContainerLayout);
        formContainerLayout.setHorizontalGroup(
            formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formContainerLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(committeeHere, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        formContainerLayout.setVerticalGroup(
            formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(committeeHere)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(453, Short.MAX_VALUE)
                .addComponent(formContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(formContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  private void radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonActionPerformed
    id.setText(btnMalaysian.isSelected() ? "IC Number" : "Passport Number");
  }//GEN-LAST:event_radioButtonActionPerformed

  private void submitButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_submitButtonActionPerformed
  } // GEN-LAST:event_submitButtonActionPerformed

    //controller actions here
    public void addLoginHereMouseListener(MouseListener l) {
        registerHere.addMouseListener(l);
    }

    public void addCommitteeHereMouseListener(MouseListener l) {
        committeeHere.addMouseListener(l);
    }

  public void addSubmitButtonEvent(java.awt.event.ActionListener l) {
    // remove existing listeners first
    ActionListener[] listeners = submitButton.getActionListeners();
    for (ActionListener ls : listeners) submitButton.removeActionListener(ls);
    submitButton.addActionListener(l);
  }

  // getter setter here
  public void setTitle(String newTitle) {
    this.title.setText(newTitle);
  }

  public void setCommitteeUserHere(String newTitle) {
    this.committeeHere.setText(newTitle);
  }

  public String getName() {
    return inputName.getText();
  }

  public String getEmail() {
    return inputEmail.getText();
  }

  public String getPhone() {
    return inputPhone.getText();
  }

  public String getPassword() {
    return String.valueOf(inputPassword.getPassword());
  } 

  public String getGender() {
    if (btnMale.isSelected()) return "M";
    return "F";
  }

  public String getBirthdate() {
    if (datePicker1.getDate() == null) return null;
    return datePicker1.getDate().toString();
  }

  public String getLocal() {
    if (btnMale.isSelected()) return "USER_LOCAL";
    return "USER_FOREIGN";
  }

  public String getIC() {
    return inputIDNumber.getText();
  }

  public void toggleCommittee(boolean b) {
      btnMale.setVisible(b);
      btnFemale.setVisible(b);
      gender.setVisible(b);
      id.setVisible(b);
      inputIDNumber.setVisible(b);
      citizenship.setVisible(b);
      btnMalaysian.setVisible(b);
      btnForeigner.setVisible(b);
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnForeigner;
    private javax.swing.JRadioButton btnMalaysian;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel citizenship;
    private javax.swing.JLabel committeeHere;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JLabel emailAddress;
    private javax.swing.JPanel formCard;
    private javax.swing.JPanel formContainer;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel id;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputIDNumber;
    private javax.swing.JTextField inputName;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JLabel name;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password1;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JLabel registerHere;
    /*
    private javax.swing.JLabel registerHere;
    */
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
