package assignment.view.user;

import javax.swing.JPanel;

/** @author rmrt1n */
public class NavigationPane extends javax.swing.JPanel {

  /** Creates new form NewJPanel */
  public NavigationPane() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        navigationPane = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        appImg = new javax.swing.JLabel();
        manageProfileTab = new javax.swing.JPanel();
        LblUser = new javax.swing.JLabel();
        ImgUser = new javax.swing.JLabel();
        appointmentTab = new javax.swing.JPanel();
        LblAppointment = new javax.swing.JLabel();
        ImgAppointment = new javax.swing.JLabel();
        vaccinationStatusTab = new javax.swing.JPanel();
        LblVaccine = new javax.swing.JLabel();
        ImgVaccine = new javax.swing.JLabel();
        logoutTab = new javax.swing.JPanel();
        txtLogout = new javax.swing.JLabel();
        imgLogout = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        setPreferredSize(new java.awt.Dimension(1280, 720));

        navigationPane.setBackground(new java.awt.Color(245, 245, 245));
        navigationPane.setPreferredSize(new java.awt.Dimension(320, 720));

        logoPanel.setBackground(new java.awt.Color(245, 245, 245));
        logoPanel.setName(""); // NOI18N

        appImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/app-large.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(appImg)
                .addGap(110, 110, 110))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(appImg)
                .addContainerGap())
        );

        manageProfileTab.setBackground(new java.awt.Color(245, 245, 245));
        manageProfileTab.setName("manageProfileTab"); // NOI18N

        LblUser.setBackground(new java.awt.Color(209, 209, 209));
        LblUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblUser.setForeground(new java.awt.Color(79, 79, 79));
        LblUser.setText("Manage Profile");

        ImgUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/people.png"))); // NOI18N

        javax.swing.GroupLayout manageProfileTabLayout = new javax.swing.GroupLayout(manageProfileTab);
        manageProfileTab.setLayout(manageProfileTabLayout);
        manageProfileTabLayout.setHorizontalGroup(
            manageProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageProfileTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ImgUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageProfileTabLayout.setVerticalGroup(
            manageProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(manageProfileTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LblUser)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        appointmentTab.setBackground(new java.awt.Color(245, 245, 245));
        appointmentTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        appointmentTab.setName("manageAppointmentTab"); // NOI18N

        LblAppointment.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblAppointment.setForeground(new java.awt.Color(79, 79, 79));
        LblAppointment.setText("Vaccination Appointment");

        ImgAppointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/calendar.png"))); // NOI18N

        javax.swing.GroupLayout appointmentTabLayout = new javax.swing.GroupLayout(appointmentTab);
        appointmentTab.setLayout(appointmentTabLayout);
        appointmentTabLayout.setHorizontalGroup(
            appointmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ImgAppointment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblAppointment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        appointmentTabLayout.setVerticalGroup(
            appointmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgAppointment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(appointmentTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LblAppointment)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        vaccinationStatusTab.setBackground(new java.awt.Color(245, 245, 245));
        vaccinationStatusTab.setName("vaccinationStatusTab"); // NOI18N

        LblVaccine.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblVaccine.setForeground(new java.awt.Color(79, 79, 79));
        LblVaccine.setText("Vaccination Status");

        ImgVaccine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/injection.png"))); // NOI18N

        javax.swing.GroupLayout vaccinationStatusTabLayout = new javax.swing.GroupLayout(vaccinationStatusTab);
        vaccinationStatusTab.setLayout(vaccinationStatusTabLayout);
        vaccinationStatusTabLayout.setHorizontalGroup(
            vaccinationStatusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vaccinationStatusTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ImgVaccine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblVaccine)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vaccinationStatusTabLayout.setVerticalGroup(
            vaccinationStatusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgVaccine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(vaccinationStatusTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LblVaccine)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        logoutTab.setBackground(new java.awt.Color(245, 245, 245));
        logoutTab.setName("logoutTab"); // NOI18N

        txtLogout.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtLogout.setForeground(new java.awt.Color(79, 79, 79));
        txtLogout.setText("Log Out");

        imgLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N

        javax.swing.GroupLayout logoutTabLayout = new javax.swing.GroupLayout(logoutTab);
        logoutTab.setLayout(logoutTabLayout);
        logoutTabLayout.setHorizontalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutTabLayout.setVerticalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addGroup(logoutTabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtLogout)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout navigationPaneLayout = new javax.swing.GroupLayout(navigationPane);
        navigationPane.setLayout(navigationPaneLayout);
        navigationPaneLayout.setHorizontalGroup(
            navigationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appointmentTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vaccinationStatusTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageProfileTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navigationPaneLayout.setVerticalGroup(
            navigationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(manageProfileTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointmentTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vaccinationStatusTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(logoutTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setEnabled(false);
        contentPanel.setPreferredSize(new java.awt.Dimension(900, 85));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigationPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getContentPanel() {
      return contentPanel;
    }

    public void addTabListeners(java.awt.event.MouseAdapter m) {
      logoutTab.addMouseListener(m);
      manageProfileTab.addMouseListener(m);
      appointmentTab.addMouseListener(m);
      vaccinationStatusTab.addMouseListener(m);
    }

    public void setTextFields(String name, String email, String password, String phone,
                              String birthdate, String gender, String ic, String address) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgAppointment;
    private javax.swing.JLabel ImgUser;
    private javax.swing.JLabel ImgVaccine;
    private javax.swing.JLabel LblAppointment;
    private javax.swing.JLabel LblUser;
    private javax.swing.JLabel LblVaccine;
    private javax.swing.JLabel appImg;
    private javax.swing.JPanel appointmentTab;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel imgLogout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel logoutTab;
    private javax.swing.JPanel manageProfileTab;
    private javax.swing.JPanel navigationPane;
    private javax.swing.JLabel txtLogout;
    private javax.swing.JPanel vaccinationStatusTab;
    // End of variables declaration//GEN-END:variables
}
