/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignment.view.user;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author rmrt1n
 */
public class VaccinationComponent extends javax.swing.JPanel {
  int vcnId;
  /**
   * Creates new form VaccinationComponent
   */
  public VaccinationComponent() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        vacCentreName = new javax.swing.JLabel();
        vacNameQty = new javax.swing.JLabel();
        bookStatus = new javax.swing.JLabel();
        datetime = new javax.swing.JLabel();
        bookBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(880, 140));

        container.setPreferredSize(new java.awt.Dimension(880, 140));

        vacCentreName.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        vacCentreName.setText("Vaccine Centre Name");

        vacNameQty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vacNameQty.setText("Vaccine name - quantity");

        bookStatus.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        bookStatus.setText("Not Booked");

        datetime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datetime.setText("start dt - end dt");

        bookBtn.setText("Book");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(vacCentreName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 487, Short.MAX_VALUE)
                        .addComponent(bookStatus))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datetime)
                            .addComponent(vacNameQty))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vacCentreName)
                    .addComponent(bookStatus))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(datetime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vacNameQty)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

  // getter setter
  public void setVcnId(int id) {
    vcnId = id;
  }

  public int getVcnId() {
    return vcnId;
  }

  public void setVacCentreName(String text) {
    vacCentreName.setText(text);
  }

  public void setDatetime(LocalDateTime start, LocalDateTime end) {
    // datetime.setText(String.format("%s - %s", start.toString(), end.toString()));
    String pattern = "EEEE, d MMMM uuuu, HH:mm";
    datetime.setText(
      DateTimeFormatter.ofPattern(pattern).format(start) +
      " - " +
      DateTimeFormatter.ofPattern(pattern).format(end)
    );
  }

  public void setVacNameQty(String name, int qty) {
    vacNameQty.setText(String.format("%s - %d left", name, qty));
  }

  public void addBookBtnListener(java.awt.event.ActionListener l) {
    bookBtn.addActionListener(l);
  }

  public void removeBookBtnListeners() {
    for (java.awt.event.ActionListener l: bookBtn.getActionListeners()) {
      bookBtn.removeActionListener(l);
    }
  }
  
  public void removeElements() {
      bookStatus.setVisible(false);
      datetime.setVisible(false);
      vacNameQty.setVisible(false);
      bookBtn.setVisible(false);
  }

  public void setBookStatus(String text) {
    bookStatus.setText(text);
  }

  public void setBookBtnStatus(String text) {
    bookBtn.setText(text);
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private javax.swing.JLabel bookStatus;
    private javax.swing.JPanel container;
    private javax.swing.JLabel datetime;
    private javax.swing.JLabel vacCentreName;
    private javax.swing.JLabel vacNameQty;
    // End of variables declaration//GEN-END:variables
}
