/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignment.view.user;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author rmrt1n
 */
public class VacStatus extends javax.swing.JPanel {

  // create new form VacStatus
  public VacStatus() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        certificate = new javax.swing.JPanel();
        certTitle = new javax.swing.JLabel();
        certName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        certIC = new javax.swing.JLabel();
        doseContainer = new javax.swing.JPanel();
        dose1 = new javax.swing.JPanel();
        dose1Title = new javax.swing.JLabel();
        dose1Date = new javax.swing.JLabel();
        dose1VacCentre = new javax.swing.JLabel();
        dose1Vaccine = new javax.swing.JLabel();
        dose2 = new javax.swing.JPanel();
        dose2Title = new javax.swing.JLabel();
        dose2VacCentre = new javax.swing.JLabel();
        dose2Date = new javax.swing.JLabel();
        dose2Vaccine = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(960, 720));

        certificate.setPreferredSize(new java.awt.Dimension(350, 550));

        certTitle.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        certTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        certTitle.setText("Covid-19 Vaccination Status");
        certTitle.setPreferredSize(new java.awt.Dimension(350, 30));

        certName.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        certName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        certName.setText("Name");
        certName.setPreferredSize(new java.awt.Dimension(350, 22));

        jSeparator1.setPreferredSize(new java.awt.Dimension(300, 10));

        certIC.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        certIC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        certIC.setText("IC/Passport");
        certIC.setPreferredSize(new java.awt.Dimension(350, 22));

        dose1.setBackground(new java.awt.Color(255, 255, 255));
        dose1.setPreferredSize(new java.awt.Dimension(330, 180));

        dose1Title.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        dose1Title.setText("Dose 1:");

        dose1Date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dose1Date.setText("Date");

        dose1VacCentre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dose1VacCentre.setText("VacCentre Name, Location");

        dose1Vaccine.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dose1Vaccine.setText("Vaccine Name");

        javax.swing.GroupLayout dose1Layout = new javax.swing.GroupLayout(dose1);
        dose1.setLayout(dose1Layout);
        dose1Layout.setHorizontalGroup(
            dose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dose1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dose1Title)
                    .addComponent(dose1Date)
                    .addComponent(dose1VacCentre)
                    .addComponent(dose1Vaccine))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dose1Layout.setVerticalGroup(
            dose1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dose1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dose1Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dose1Date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dose1VacCentre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dose1Vaccine)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        dose2.setBackground(new java.awt.Color(255, 255, 255));
        dose2.setPreferredSize(new java.awt.Dimension(330, 180));

        dose2Title.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        dose2Title.setText("Dose 2:");

        dose2VacCentre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dose2VacCentre.setText("VacCentre Name, Location");

        dose2Date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dose2Date.setText("Date");

        dose2Vaccine.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dose2Vaccine.setText("Vaccine Name");

        javax.swing.GroupLayout dose2Layout = new javax.swing.GroupLayout(dose2);
        dose2.setLayout(dose2Layout);
        dose2Layout.setHorizontalGroup(
            dose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dose2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dose2Title)
                    .addComponent(dose2Date)
                    .addComponent(dose2VacCentre)
                    .addComponent(dose2Vaccine))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dose2Layout.setVerticalGroup(
            dose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dose2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dose2Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dose2Date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dose2VacCentre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dose2Vaccine)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout doseContainerLayout = new javax.swing.GroupLayout(doseContainer);
        doseContainer.setLayout(doseContainerLayout);
        doseContainerLayout.setHorizontalGroup(
            doseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doseContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(doseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dose1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(dose2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addContainerGap())
        );
        doseContainerLayout.setVerticalGroup(
            doseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doseContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout certificateLayout = new javax.swing.GroupLayout(certificate);
        certificate.setLayout(certificateLayout);
        certificateLayout.setHorizontalGroup(
            certificateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(certificateLayout.createSequentialGroup()
                .addGroup(certificateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(certTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(certName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(certIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(certificateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(certificateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(certificateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(doseContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        certificateLayout.setVerticalGroup(
            certificateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(certificateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(certTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(certName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(certIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(doseContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STATUS: UNVACCINATED");
        jLabel1.setPreferredSize(new java.awt.Dimension(960, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(certificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(certificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  // getter setter
  public void setUser(String name, String ic) {
    certName.setText(name);
    certIC.setText(ic);
  }

  private String pattern = "d MMMM uuuu";
  public void setDose1(LocalDateTime startDate, LocalDateTime endDate, 
                       String vacCentreName, String vacCentreLocation, String vaccineName) {
    dose1Date.setText(
      DateTimeFormatter.ofPattern(pattern).format(startDate)
    );
    dose1VacCentre.setText(String.format("Location: %s, %s", vacCentreName, vacCentreLocation));
    dose1Vaccine.setText("Vaccine: " + vaccineName);
  }

  public void setDose2(LocalDateTime startDate, LocalDateTime endDate, String vacCentreName,
                       String vacCentreLocation, String vaccineName) {
    dose2Date.setText(
      DateTimeFormatter.ofPattern(pattern).format(startDate)
    );
    dose2VacCentre.setText(String.format("Location: %s, %s", vacCentreName, vacCentreLocation));
    dose2Vaccine.setText("Vaccine: " + vaccineName);
  }

  public void setUnvac(int dose) {
    // Unvaccinated
    if(dose == 0){
      dose1VacCentre.setText("");
      dose1Date.setText("");
      dose1Vaccine.setText("");
    }

    // Partially vaccinated
    dose2VacCentre.setText("");
    dose2Date.setText("");
    dose2Vaccine.setText("");  
  }

  public void setVacStatus(String status) {
    jLabel1.setText("STATUS: " + status);
  }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel certIC;
    private javax.swing.JLabel certName;
    private javax.swing.JLabel certTitle;
    private javax.swing.JPanel certificate;
    private javax.swing.JPanel dose1;
    private javax.swing.JLabel dose1Date;
    private javax.swing.JLabel dose1Title;
    private javax.swing.JLabel dose1VacCentre;
    private javax.swing.JLabel dose1Vaccine;
    private javax.swing.JPanel dose2;
    private javax.swing.JLabel dose2Date;
    private javax.swing.JLabel dose2Title;
    private javax.swing.JLabel dose2VacCentre;
    private javax.swing.JLabel dose2Vaccine;
    private javax.swing.JPanel doseContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
